version: '3.8'

services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=financial_db

  auth-service:
    build:
      context: ./services/auth-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/financial_auth
      - JWT_SECRET=your-secret-key
    depends_on:
      - mongodb

  invoice-service:
    build:
      context: ./services/invoice-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/financial_invoices
    depends_on:
      - mongodb

  ledger-service:
    build:
      context: ./services/ledger-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/financial_ledger
    depends_on:
      - mongodb

  user-service:
    build:
      context: ./services/user-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/financial_users
    depends_on:
      - mongodb

  web-ui:
    build:
      context: ./web-ui
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - auth-service

volumes:
  mongo-data: