version: '3.8'

services:
  product-service:
    build:
      context: ./services/product-service
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - inventory-network

  order-service:
    build:
      context: ./services/order-service
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    networks:
      - inventory-network

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    networks:
      - inventory-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge

volumes:
  db-data:
    driver: local