
services:
  auth-service:
    build:
      context: ./services/auth-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  ledger-service:
    build:
      context: ./services/ledger-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production

  invoice-service:
    build:
      context: ./services/invoice-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production

  user-service:
    build:
      context: ./services/user-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production

networks:
  default:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  postgres-data:
    driver: local
