version: '3.8'

services:
  auth-service:
    build:
      context: ./services/auth-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongo:27017/auth
    depends_on:
      - mongo

  product-service:
    build:
      context: ./services/product-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongo:27017/products
    depends_on:
      - mongo

  order-service:
    build:
      context: ./services/order-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongo:27017/orders
    depends_on:
      - mongo

  user-service:
    build:
      context: ./services/user-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongo:27017/users
    depends_on:
      - mongo

  gateway:
    build:
      context: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - product-service
      - order-service
      - user-service

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: