version: '3.8'

services:
  auth-service:
    build:
      context: ./services/auth-service
    ports:
      - "3001:3000"
    networks:
      - erp-network

  inventory-service:
    build:
      context: ./services/inventory-service
    ports:
      - "3002:3000"
    networks:
      - erp-network

  order-service:
    build:
      context: ./services/order-service
    ports:
      - "3003:3000"
    networks:
      - erp-network

  user-service:
    build:
      context: ./services/user-service
    ports:
      - "3004:3000"
    networks:
      - erp-network

  web-client:
    build:
      context: ./web-client
    ports:
      - "3000:3000"
    networks:
      - erp-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - erp-network

networks:
  erp-network:
    driver: bridge

volumes:
  db-data: {}