version: '3.8'

services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=erp_system
    networks:
      - erp-network

  auth-service:
    build:
      context: ./services/auth-service
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/erp_auth
      - JWT_SECRET=erp-secret-key
    depends_on:
      - mongodb
    networks:
      - erp-network

  inventory-service:
    build:
      context: ./services/inventory-service
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/erp_inventory
    depends_on:
      - mongodb
    networks:
      - erp-network

  order-service:
    build:
      context: ./services/order-service
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/erp_orders
    depends_on:
      - mongodb
    networks:
      - erp-network

  user-service:
    build:
      context: ./services/user-service
    ports:
      - "3004:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/erp_users
    depends_on:
      - mongodb
    networks:
      - erp-network

  web-client:
    build:
      context: ./web-client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - auth-service
      - inventory-service
      - order-service
      - user-service
    networks:
      - erp-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web-client
    networks:
      - erp-network

networks:
  erp-network:
    driver: bridge

volumes:
  db-data: